### PR TITLE
Add usage of snippet to live version

### PR DESCRIPTION
**Pull request by TobiasFeld22**

### CODE REVIEW

**Review by advaith1 — CHANGES_REQUESTED** [review]
"Add usage of snippet" just adds a new Method to the snippets page: `.()`. It doesnt show any information related to using snippets.

**Comment by TobiasFeld22** [comment]
It shows .\<nameofsnippet\>, which means like put the name of the snippet here. Honestly i don't know how to explain / put that there better

**Comment by advaith1** [comment]
Looks like that's being parsed as HTML since the <> isnt escaped

**Comment by TobiasFeld22** [comment]
Ah like that, that makes sense.

**Pull request merged**
